### ISSUE TITLE
Can't start the app

### ISSUE THREAD

**Issue by azzamsa** [khlieng/dispatch#75]
I am trying to start dispatch. After many attemps, It still stuck.

I've disabled `verify_certificates = false` and disabled the https. But still get `Connection reset`.

```toml
# IP address to listen on, leave empty to listen on anything
address = ""
#port = 80
port = 8084
# Run ident daemon on port 113
identd = true
# Hex encode the users IP and use it as the ident
hexIP = false
# Automatically reply to common CTCP messages
auto_ctcp = true
# Verify the certificate chain presented by the IRC server, if this check fails
# the user will be able to choose to still connect
#verify_certificates = true
verify_certificates = false

# Defaults for the client connect form
[defaults]
name = "freenode"
host = "chat.freenode.net"
port = 6697
channels = [
  "#dispatch"
]
server_password = ""
ssl = true
# Only allow a nick to be filled in
readonly = false
# Show server and channel info when readonly is enabled
show_details = false

[https]
#enabled = true
enabled = false
port = 443
# Path to your cert and private key if you are not using
# the Let's Encrypt integration
cert = ""
key = ""

[letsencrypt]
# Your domain or subdomain, if not set a certificate will be
# fetched for whatever domain dispatch gets accessed through
domain = ""
# An email address lets you recover your accounts private key
email = ""

# Not implemented
[auth]
# Allow usage without being logged in, all channels and settings get
# transferred when logging in or registering
anonymous = true
# Enable username/password login
login = true
# Enable username/password registration
registration = true

[auth.providers.github]
key = ""
secret = ""

[auth.providers.facebook]
key = ""
secret = ""

[auth.providers.google]
key = ""
secret = ""

[auth.providers.twitter]
key = ""
secret = ""

[dcc]
# Receive files through DCC, the user gets to choose if they want to accept the file,
# the file download then gets proxied to the user
enabled = true

[dcc.autoget]
# Instead of proxying the file download directly to the user, dispatch automatically downloads
# DCC files and sends a download link to the user once its done
enabled = false
# Delete the file after the user has downloaded it once
delete = true
# Delete the file after a certain time period of inactivity, not implemented yet
delete_after = "30m"

[proxy]
# Dispatch will make all outgoing connections through the specified proxy when enabled
enabled = false
protocol = "socks5"
host = "127.0.0.1"
port = 1080
username = ""
password = ""

# HTTP Strict-Transport-Security
[https.hsts]
enabled = false
max_age = 31536000
include_subdomains = false
preload = false

# Add your own HTTP headers to the index page
[headers]
# X-Example = "Rainbows"
```

Accessing `MYIP:8084` gives me:

![image](https://user-images.githubusercontent.com/17734314/105567476-b7ff3280-5d64-11eb-94fc-84bf5730bdf5.png)

```bash
root@foo:~/godispatch/data# docker run -p 8084:443 -v /root/godispatch/data:/data khlieng/dispatch

    ____   _                     _         _
   |  _ \ (_) ___  _ __    __ _ | |_  ___ | |__
   | | | || |/ __|| '_ \  / _  || __|/ __|| '_ \
   | |_| || |\__ \| |_) || (_| || |_| (__ | | | |
   |____/ |_||___/| .__/  \__,_| \__|\___||_| |_|
                  |_|

   v0.7 + 95 commits
   Commit: 721492ca
   Build Date: 10 Dec 2020, 08:09:07
   Runtime: go1.15.6

2021/01/23 03:10:12 Storing data at /data
2021/01/23 03:10:12 [Init] 0 sessions
2021/01/23 03:10:12 [Init] 0 users
2021/01/23 03:10:12 [HTTP] Listening on port 8084
```

**Comment by khlieng** [comment]
Have you tried passing `-p 8084:80` instead of `-p 8084:443` to docker?

**Comment by azzamsa** [comment]
the strange thing is. I need to change the value in `config.toml`. becase the docker args is not respected.

![image](https://user-images.githubusercontent.com/17734314/105575446-4cd25200-5d9e-11eb-8a13-5bd242332ea3.png)

**Comment by azzamsa** [comment]
It works, after I change the `port` and https `port` to the same value:

```toml
#port = 80
port = 8085


[https]
#enabled = true
enabled = false
#port = 443
port = 8085
```

![image](https://user-images.githubusercontent.com/17734314/105575515-cff3a800-5d9e-11eb-8fff-6fa5b23cae1a.png)
